version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/run:
          node/test
  integrateFrontend:
    machine: true
    steps:
      - run: git clone https://github.com/shagaut/3w5-h22-tp2-frontend.git frontend
      - run: git clone https://github.com/shagaut/3w5-h22-tp2-backend.git backend
      - run: cd frontend && npm i && npm build
      - run: cd ../backend && mkdir public
      - run: cp -rT frontend/public backend/public
      - persist_to_workspace:
          root: .
          paths:
            - backend
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: cd backend && ls -Rl
    
workflows:
  workflow-tp2:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - deploy:
          requires:
            - integrateFrontend